ncs-jss/HTTP_200

HTTP_200/templates/bookmark.html, notices/admin.py, notices/migrations/0006_bookmarkednotice_pinned.py, notices/models.py, notices/urls.py, notices/views.py
@DESHRAJ 
Please create this feature in v.1 so that we have more parity between old and new infocenter. 
( Will not touch again any v.1.2 issue without prior notice :smile: )
=> creating 'pin it to top' option in bookmarks #42

message/admin.py, message/migrations/0001_initial.py, message/models.py, message/tests.py, message/views.py
Revert "Including the group while doing signup"
This reverts commit 7228e8819814b801ec652f835819f8a6acc39848.
=> creating message models

HTTP_200/settings.py, notices/admin.py, profiles/admin.py, requirements.txt
modified:   notices/admin.py
modified:   profiles/admin.py
modified : profiles/admin.py
modified: settings.py
=> Added Export and Import to Student admin page 

HTTP_200/templates/index.html
The icons in the sidebar were not according to he menu - fixed 
Properly spaced subfooter with white color instead of black to improve visibility 
Styling is very small so done inline
=> Fixed the icons in sidebar and improved subfooter

HTTP_200/templates/about.html, HTTP_200/templates/account/password_change.html, HTTP_200/templates/bookmark.html, HTTP_200/templates/comingsoon.html, HTTP_200/templates/contact.html, HTTP_200/templates/index.html, HTTP_200/templates/notices/list.html, HTTP_200/templates/notices/my_uploaded_notices.html, HTTP_200/templates/notices/notice_create.html, HTTP_200/templates/profiles/profile.html
The name of our college has a typo error!! 
JSS Mailbox is repeated twice which i have corrected by replacing it with JSS Website!!!
IS it OK??
=> Typo Error

HTTP_200/templates/account/login.html, HTTP_200/templates/account/password_reset.html, HTTP_200/templates/account/password_reset_done.html, HTTP_200/templates/account/password_reset_from_key.html, HTTP_200/templates/account/password_reset_from_key_done.html
=> Forget Password: Frontend Files added for Forget Password Feature.

HTTP_200/templates/account/email/password_reset_key_message.txt
=> Forget Password: Email content Modified for Password Reset.

HTTP_200/templates/profiles/profile.html
=> Profile : Added MCA Field in Departments for Faculty User.

HTTP_200/templates/index.html
=> Links: Added NPTEL and Sakshat Links on the Front Page.

profiles/admin.py
=> Details of Contact Messages shown in admin & search added in FacultyAdmin.

wifi/admin.py
There is an error in the code due to flake8 regarding ',' because of which the build was failed. I have fixed it.
=> Flake8 error fix

HTTP_200/templates/singleuser.html, HTTP_200/templates/singleuserform.html, profiles/models.py, profiles/views.py
=> Add new courses in single user creation form.

wifi/admin.py, wifi/forms.py, wifi/models.py, wifi/views.py
=> Fixed flake8 errors and fixed build #219

wifi/admin.py, wifi/forms.py, wifi/models.py, wifi/views.py
=> Revert "Fixed flake8 errors and fixed build #219"

HTTP_200/static/css/default.css, HTTP_200/templates/about.html, HTTP_200/templates/account/password_change.html, HTTP_200/templates/contact.html, HTTP_200/templates/index.html, HTTP_200/templates/notices/my_uploaded_notices.html, HTTP_200/templates/profiles/profile.html, HTTP_200/templates/wifi/facultywifiform.html, HTTP_200/templates/wifi/studentwifiform.html
=> Fixed footer and table borders in notices

notices/decorators.py, notices/views.py, wifi/models.py, wifi/views.py
=> Bare except statements removed

HTTP_200/templates/about.html, HTTP_200/templates/account/password_change.html, HTTP_200/templates/bookmark.html, HTTP_200/templates/bulkuser.html, HTTP_200/templates/bulkuserform.html, HTTP_200/templates/comingsoon.html, HTTP_200/templates/contact.html, HTTP_200/templates/index.html, HTTP_200/templates/notices/list.html, HTTP_200/templates/notices/my_uploaded_notices.html, HTTP_200/templates/profiles/profile.html, HTTP_200/templates/singleuser.html, HTTP_200/templates/singleuserform.html, HTTP_200/templates/wifi/facultywifiform.html, HTTP_200/templates/wifi/studentwifiform.html
In this PR-
Link for JSS Library is replaced with [National Digital Library of India](https://ndl.iitkgp.ac.in/)
Broken links of Mechanical Department and Instrumentation and Control fixed.
@RishabhJain2018 Please review.
fixes #115
closes #235
=> Update 'Quick Links' section of all templates.

HTTP_200/templates/about.html, HTTP_200/templates/account/password_change.html, HTTP_200/templates/bookmark.html, HTTP_200/templates/bulkuser.html, HTTP_200/templates/bulkuserform.html, HTTP_200/templates/comingsoon.html, HTTP_200/templates/contact.html, HTTP_200/templates/index.html, HTTP_200/templates/notices/list.html, HTTP_200/templates/notices/my_uploaded_notices.html, HTTP_200/templates/notices/notice_create.html, HTTP_200/templates/profiles/profile.html, HTTP_200/templates/singleuser.html, HTTP_200/templates/singleuserform.html, HTTP_200/templates/wifi/facultywifiform.html, HTTP_200/templates/wifi/studentwifiform.html
Quick links restructured the following way-
closes #235 
@RishabhJain2018 Sir, please review the PR.
=> Quick links restructured

apps/notices/decorators.py, apps/notices/views.py
=> Build fixes

HTTP_200/static/js/main.js
Adds 
- ```3``` for year drop-down of MCA-department.
- ```CSE3``` section for CSE-department.
closes #240 
@RishabhJain2018 Please review. :slightly_smiling_face:
=> Dropdown options updated

README.md
This PR adds the coverage badge by updating the ```README.md```
fixes #236 
@RishabhJain2018 Please review this PR. :slightly_smiling_face:
=> Activate the coverage badge

apps/profiles/migrations/0002_auto_20200130_1800.py
=> Added missing migration file
